using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using NaughtyAttributes;


/// <summary>
/// 
/// </summary>
public class RowController : MonoBehaviour
{

    #region Inspector Fields

    [SerializeField]
    private Transform m_topHand;
    [SerializeField]
    private Transform m_bottomHand;

    [SerializeField, BoxGroup("Settings"), Range(0.0f, 1.0f)]
    private float m_armRange = 1;

    [SerializeField, BoxGroup("Settings"), Range(0.0f, 1.0f)]
    private float m_armSpeed = 0.2f;

    [SerializeField, BoxGroup("Input")]
    private InputActionProperty m_inputAxis;
    #endregion Inspector Fields

    #region Private Fields
  
    #endregion Private Fields

    #region Getters

    #endregion Getters



    #region MonoBehaviour Functions




    /// <summary>
    /// OnEnable is called when the object becomes enabled and active.
    /// </summary>
    private void OnEnable()
    {
        
    }

    /// <summary>
	/// OnDisable is called when the behaviour becomes disabled.
    /// </summary>
    private void OnDisable()
    {
    
    }

    /// <summary>
    /// Update is called once per frame
    /// </summary>
    private void Update()
    {
    
    }

    #endregion MonoBehaviour Functions

    #region Class Functionality
    
    #endregion Class Functionality

    #region Editor Functions
    /// <summary>
    /// Called when the Component is created or Reset from the Inspector
    /// </summary>
    private void Reset()
    {
        //useful for finding components on creation
    } 
    #endregion Editor Functions

}